# Cargar rutas definidas en los controladores (Anotaciones #[Route])
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Configuraci√≥n manual de rutas (si es necesaria)
api_login_check:
    path: /api/login_check

# API Platform (debe ir al final para no "comerse" otras rutas /api)
api_platform:
    resource: .
    type: api_platform
    prefix: /api
